use_frameworks!

platform :ios, '9.0'

target 'QIJKPlayer_Example' do
  pod 'QIJKPlayer', :path => '../'

  target 'QIJKPlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
